spring:
  application:
    name: apigatewayserver
server:
  port: 8765
zuul:
  ignored-services: "*"
  routes:
    vendormicro:
      path: /vendor/**
      serviceId: vendormicro
    categorymicro:
      path: /category/**
      serviceId: categorymicro
    productmicro:
      path: /product/**
      serviceId: productmicro
    usermicro:
      path: /user/**
      serviceId: usermicro
eureka:
  instance:
    preferIpAddress: true
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/